name: Bump Version
on:
    workflow_dispatch:
        inputs:
            type:
                description: "Type of version (`major`, `minor`, `patch`)"
                required: true
                default: "patch"
jobs:
    bump:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  persist-credentials: true # This allows the use of GITHUB_TOKEN
                  fetch-depth: 0 # Fetch all history for all tags and branches
                  token: ${{secrets.GITHUB_TOKEN}} # Use GITHUB_TOKEN for checkout

            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "14.x" # Adjust node version as needed

            - name: Update version
              id: version
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  npm version ${{ github.event.inputs.type }}
                  echo "::set-output name=tag::$(git describe --abbrev=0)"

            - name: Update manifest version
              uses: jossef/action-set-json-field@v1
              with:
                  file: manifest.json
                  field: version
                  value: ${{ steps.version.outputs.tag }}

            - name: Commit manifest
              run: |
                  git add -u
                  git commit --amend --no-edit
                  git tag -fa ${{ steps.version.outputs.tag }} -m "${{ steps.version.outputs.tag }}"

            - name: Push changes
              uses: ad-m/github-push-action@v0.6.0
              with:
                  github_token: ${{secrets.GITHUB_TOKEN}} # Use GITHUB_TOKEN for push
                  tags: true
                  branch: ${{ github.ref }}